# Generated by Django 4.2.5 on 2023-11-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amplificadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_artefacto', models.CharField(max_length=50)),
                ('tipo_artefacto', models.CharField(max_length=50)),
                ('precio_amplificador', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Instrumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_instrumento', models.CharField(max_length=50)),
                ('tipo_instrumento', models.CharField(max_length=50)),
                ('precio_instrumento', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Varios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronico', models.CharField(max_length=50)),
                ('tipo_electronico', models.CharField(max_length=50)),
                ('precio_varios', models.FloatField()),
            ],
        ),
    ]
