# Generated by Django 4.2.5 on 2023-11-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0002_delete_varios_instrumentos_descripcion_instrumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentos',
            name='fecha_incorporacion',
            field=models.DateField(null=True),
        ),
    ]
