# Generated by Django 4.2.5 on 2023-11-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0003_instrumentos_fecha_incorporacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentos',
            name='descripcion_instrumento',
            field=models.TextField(),
        ),
    ]
