# Generated by Django 4.2.5 on 2023-11-17 18:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0005_alter_instrumentos_descripcion_instrumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentos',
            name='descripcion_instrumento',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
