# Generated by Django 4.2.5 on 2023-11-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0006_alter_instrumentos_descripcion_instrumento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amplificadores',
        ),
        migrations.AddField(
            model_name='instrumentos',
            name='imagen_instrumento',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
