# Generated by Django 4.2.5 on 2023-11-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0007_delete_amplificadores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentos',
            name='imagen_instrumento',
            field=models.ImageField(blank=True, null=True, upload_to='Instrumentos_images/'),
        ),
    ]
